version: 2

# =============================================================================
# DIMENSION TABLES
# =============================================================================

models:
  # ---------------------------------------------------------------------------
  # dim_movies
  # ---------------------------------------------------------------------------
  - name: dim_movies
    description: "Movie dimension with all movie attributes"
    columns:
      - name: movie_id
        description: "Primary key - Movie rank (1-95)"
        tests:
          - not_null
          - unique
      
      - name: movie_title
        description: "Movie title"
        tests:
          - not_null
      
      - name: release_year
        description: "Year of release"
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_id

  # ---------------------------------------------------------------------------
  # dim_genres
  # ---------------------------------------------------------------------------
  - name: dim_genres
    description: "Genre lookup dimension"
    columns:
      - name: genre_id
        description: "Primary key - Auto-generated ID"
        tests:
          - not_null
          - unique
      
      - name: genre_name
        description: "Genre name"
        tests:
          - not_null
          - unique

  # ---------------------------------------------------------------------------
  # dim_actors
  # ---------------------------------------------------------------------------
  - name: dim_actors
    description: "Actor lookup dimension"
    columns:
      - name: actor_id
        description: "Primary key - Auto-generated ID"
        tests:
          - not_null
          - unique
      
      - name: actor_name
        description: "Actor name"
        tests:
          - not_null
          - unique

  # ---------------------------------------------------------------------------
  # dim_directors
  # ---------------------------------------------------------------------------
  - name: dim_directors
    description: "Director lookup dimension"
    columns:
      - name: director_id
        description: "Primary key - Auto-generated ID"
        tests:
          - not_null
          - unique
      
      - name: director_name
        description: "Director name"
        tests:
          - not_null
          - unique

  # ---------------------------------------------------------------------------
  # dim_countries
  # ---------------------------------------------------------------------------
  - name: dim_countries
    description: "Country lookup dimension"
    columns:
      - name: country_id
        description: "Primary key - Auto-generated ID"
        tests:
          - not_null
          - unique
      
      - name: country_name
        description: "Country name"
        tests:
          - not_null
          - unique

  # ---------------------------------------------------------------------------
  # dim_languages
  # ---------------------------------------------------------------------------
  - name: dim_languages
    description: "Language lookup dimension"
    columns:
      - name: language_id
        description: "Primary key - Auto-generated ID"
        tests:
          - not_null
          - unique
      
      - name: language_name
        description: "Language name"
        tests:
          - not_null
          - unique

  # ---------------------------------------------------------------------------
  # dim_time
  # ---------------------------------------------------------------------------
  - name: dim_time
    description: "Time dimension (year-based)"
    columns:
      - name: time_id
        description: "Primary key - Year (1931-2019)"
        tests:
          - not_null
          - unique
      
      - name: year
        description: "Full year"
        tests:
          - not_null

# =============================================================================
# BRIDGE TABLES
# =============================================================================

  # ---------------------------------------------------------------------------
  # bridge_movie_genre
  # ---------------------------------------------------------------------------
  - name: bridge_movie_genre
    description: "Many-to-many relationship between movies and genres"
    columns:
      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      
      - name: genre_id
        description: "Foreign key to dim_genres"
        tests:
          - not_null
          - relationships:
              to: ref('dim_genres')
              field: genre_id

  # ---------------------------------------------------------------------------
  # bridge_movie_actor
  # ---------------------------------------------------------------------------
  - name: bridge_movie_actor
    description: "Many-to-many relationship between movies and actors"
    columns:
      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      
      - name: actor_id
        description: "Foreign key to dim_actors"
        tests:
          - not_null
          - relationships:
              to: ref('dim_actors')
              field: actor_id

  # ---------------------------------------------------------------------------
  # bridge_movie_director
  # ---------------------------------------------------------------------------
  - name: bridge_movie_director
    description: "Many-to-many relationship between movies and directors"
    columns:
      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      
      - name: director_id
        description: "Foreign key to dim_directors"
        tests:
          - not_null
          - relationships:
              to: ref('dim_directors')
              field: director_id

  # ---------------------------------------------------------------------------
  # bridge_movie_country
  # ---------------------------------------------------------------------------
  - name: bridge_movie_country
    description: "Many-to-many relationship between movies and countries"
    columns:
      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      
      - name: country_id
        description: "Foreign key to dim_countries"
        tests:
          - not_null
          - relationships:
              to: ref('dim_countries')
              field: country_id

  # ---------------------------------------------------------------------------
  # bridge_movie_language
  # ---------------------------------------------------------------------------
  - name: bridge_movie_language
    description: "Many-to-many relationship between movies and languages"
    columns:
      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      
      - name: language_id
        description: "Foreign key to dim_languages"
        tests:
          - not_null
          - relationships:
              to: ref('dim_languages')
              field: language_id

# =============================================================================
# FACT TABLE
# =============================================================================

  # ---------------------------------------------------------------------------
  # fact_movie_performance
  # ---------------------------------------------------------------------------
  - name: fact_movie_performance
    description: "Fact table with movie performance metrics"
    columns:
      - name: movie_id
        description: "Foreign key to dim_movies"
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      
      - name: time_id
        description: "Foreign key to dim_time"
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_id
      
      - name: box_office_millions
        description: "Box office revenue in millions USD"
      
      - name: oscars_won
        description: "Number of Oscars won"
      
      - name: is_masterpiece
        description: "Flag: 1 if IMDb >= 9.0"
        tests:
          - accepted_values:
              values: [0, 1]
      
      - name: is_blockbuster
        description: "Flag: 1 if box office >= 1000M"
        tests:
          - accepted_values:
              values: [0, 1]